name: Sculpting Action Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: suziwen/testactiontarget
          ref: refs/heads/main
          fetch-depth: 1
          path: 'testaction/public'
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
      - uses: suziwen/gatsby-gh-pages-action@v2.2.9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          deploy-repo: testactiontarget
